fix: following symlinks should be configurable
By default, following symlinks were enabled, causing issues with certain paths,
for example, when direnv is enabled and no gitignore exists (or does not contain
direnv), WalkDir tries to access certain symlinked files, causing:

```
Error: NotFound, message: "No such file or directory"
```

Disabling follow-symlinks by default and making it configurable fixes this issue

Closes: #4

Signed-off-by: Chinmay D. Pai <chinmaydpai@gmail.com>